name: build

on:
  push:
    paths:
      - ".github/workflows/go.yml"
      - "**.go"

jobs:
  job1:
    name: ci pipeline
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: build
      run: go build -v

